<?php

namespace App\Http\Controllers;

use App\Models\Kredit;
use App\Models\Setting;
use Codedge\Fpdf\Fpdf\Fpdf;
use Illuminate\Http\Request;

class CetakTagihanController extends Controller
{
    protected $pdf;


    public function __construct()
    {
        $this->pdf = new Fpdf;
    }

    public function header()
    {
        $setting = Setting::first();
        //Header
        $this->pdf->SetFont('Arial', 'B', 18);
        $this->pdf->Cell(30);
        $this->pdf->Cell(140, 5, $setting->nama_toko, 0, 1, 'C');

        $this->pdf->SetFont('Arial', 'B', 13);
        $this->pdf->SetTextColor(0, 0, 0);
        $this->pdf->Cell(30);
        $this->pdf->Cell(140, 9, 'JUAL BELI MOTOR BEKAS CASH/KREDIT', 0, 1, 'C');

        $this->pdf->SetFont('Arial', '', 10);
        $this->pdf->SetTextColor(0);
        $this->pdf->Cell(30);
        $this->pdf->Cell(140, 5, strtoupper($setting->alamat_toko), 0, 1, 'C');

        // Menambahkan garis header
        $this->pdf->SetLineWidth(1);
        $this->pdf->Line(10, 36, 200, 36);
        $this->pdf->SetLineWidth(0);
        $this->pdf->Line(10, 37, 200, 37);
        $this->pdf->Ln();
        //Header
    }

    public function cetak_tagihan(Request $request)
    {
        $setting = Setting::first();
        $data = Kredit::get_data($request->unique);
        //SURAT JALAN
        if ($request->size == "A4") {
            $this->pdf->AddPage('P', 'A4');
            $this->header();
            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'SURAT JALAN', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            $this->pdf->Cell(44, 7, 'Yang bertanda tangan dibawah ini', 0, '0', 'L', true);
            $this->pdf->Cell(4, 7, ':', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($setting->nama_pemilik), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($setting->alamat_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(100, 7, 'Dengan ini menyerahkan 1(satu) unit sepeda motor:', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->tahun_pembuatan, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Nama Nasabah', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, $data->alamat, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Hp', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, $data->no_telepon, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(145, 181);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()), 0, 'L',  true);
            $this->pdf->SetXY(9, 186);
            $this->pdf->MultiCell(55, 5, 'Yang menerima', 0, 'L',  true);
            $this->pdf->SetXY(145, 186);
            $this->pdf->MultiCell(55, 5, 'Yang menyerahkan', 0, 'L',  true);
            $this->pdf->SetXY(9, 220);
            $this->pdf->MultiCell(55, 5, '(..............................................)', 0, 'L',  true);
            $this->pdf->SetXY(145, 220);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);
            $this->pdf->Ln();

            //KWITANSI PELUNASAN
            $this->pdf->AddPage('P', 'A4');
            $this->header();

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'KWITANSI PELUNASAN', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 7, 'Sudah Terima Dari', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($request->nama_leasing), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Nama Nasabah', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Banyaknya Uang', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, terbilang($data->pencairan) . " Rupiah", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Untuk Pembayaran', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, 'Pelunasan 1 (unit) Sepeda Motor dengan data-data Sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->tahun_pembuatan, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Pelunasan', 0, '0', 'L', true);
            $this->pdf->Cell(38, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, rupiah($data->pencairan), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(145, 181);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()), 0, 'L',  true);
            $this->pdf->SetXY(145, 220);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);
            $this->pdf->Ln();


            //KWITANSI UANG MUKA
            $this->pdf->AddPage('P', 'A4');
            $this->header();

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'KWITANSI UANG MUKA', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 7, 'Sudah Terima Dari', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($request->nama_leasing), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Nama Nasabah', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Banyaknya Uang', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, terbilang($data->dp_po) . " Rupiah", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Untuk Pembayaran', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, 'Down Payment 1 (unit) Sepeda Motor dengan data-data Sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->tahun_pembuatan, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Uang Muka', 0, '0', 'L', true);
            $this->pdf->Cell(38, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, rupiah($data->dp_po), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(145, 181);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()), 0, 'L',  true);
            $this->pdf->SetXY(145, 220);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);
            $this->pdf->Ln();

            //TANPA JUDUL 1
            $this->pdf->AddPage('P', 'A4');
            $this->header();

            $this->pdf->Ln();
            $this->pdf->Ln();

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 7, 'Nama Nasabah', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Jenis Kendaraan', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, "SEPEDA MOTOR", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->tahun_pembuatan . '   /' . $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Asli", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Duplikat", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'Faktur', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'Kwitansi Blangko BBN atas nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'FC KTP atas nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'FC STNK dan Nota Pajak', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'Nomor Polisi Sesuai STNK & BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'Noka dan Nosin Sesuai STNK & BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(9, 220);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()) . ',', 0, 'L',  true);
            $this->pdf->SetXY(9, 225);
            $this->pdf->MultiCell(55, 5, 'Yang menyatakan,', 0, 'L',  true);
            $this->pdf->SetXY(9, 259);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);

            //KOTAK CEKLIS
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetDrawColor(0, 0, 0);
            //BPKB
            $this->pdf->SetXY(85, 115);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 115);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            //Faktur
            $this->pdf->SetXY(85, 122);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 122);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //Kwitansi Blangko BBN atas nama BPKB
            $this->pdf->SetXY(85, 129);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 129);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //FC KTP atas nama BPKB
            $this->pdf->SetXY(85, 136);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 136);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //FC STNK dan Nota Pajak
            $this->pdf->SetXY(85, 143);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 143);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //Nomor Polisi Sesuai STNK & BPKB
            $this->pdf->SetXY(85, 150);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 150);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //Noka dan Nosin Sesuai STNK & BPKB
            $this->pdf->SetXY(85, 157);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 157);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //Pernyataan
            $this->pdf->SetXY(9, 181);
            $this->pdf->MultiCell(190, 7, 'Apabila dikemudian hari diketahui bahwa surat-surat kendaraan tersebut di atas PALSU dan atau SEDANG DALAM PEMBLOKIRAN, maka dengan ini kami (dealer / sub dealer / showroom / perorangan) menyatakan "akan membeli kembali atau melunasi kendaraan tersebut di atas kepada ' . strtoupper($request->nama_leasing) . ' sesuai dengan perhitungan pelunasan dari ' . strtoupper($request->nama_leasing) . ' selambat-lambatnya 1 (satu) minggu sejak adanya pemberitahuan".', 0, 'J',  true);
            $this->pdf->Ln();

            //SURAT PERNYATAAN
            $this->pdf->AddPage('P', 'A4');
            $this->header();

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'SURAT PERNYATAAN', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 6.7, 'Yang bertanda tangan dibawah ini', 0, '0', 'L', true);
            $this->pdf->Cell(4, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_pemilik), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Jabatan', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, "OWNER", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Dealer/Showroom', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, '', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, '', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->alamat_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, 'Menyatakan bahwa BPKB dengan data sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Jenis', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, 'SEPEDA MOTOR', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->tahun_pembuatan . '   /' . $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, 'Dengan ini menyatakan bahwa :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, '1. Telah menjual kendaraan tersebut kepada :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->alamat, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, '2. bahwa kendaraan tersebut diatas benar-benar milik penandatangan sendiri berdasarkan jual beli yang sah dari pemilik semula, yaitu :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->alamat_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, '3. Bahwa kendaraan tersebut di atas BUKAN TITIPAN PIHAK LAIN.', 0, '0', 'L', true);

            $this->pdf->SetXY(10, 197);
            $this->pdf->MultiCell(190, 6.7, '4. Bahwa penjulan kendaraan tersebut adalah penjualan langsung kepada pembeli tersebut di atas dengan jasa ' . strtoupper($request->nama_leasing) . ' sebagai kreditor dan BUKAN TRANSAKSI LEASE BACK atau menjaminkan kendaraan untuk mendapatkan uang tunai dengan penandatanganan sebagai atau menjaminkan kendaraan untuk mendapatkan uang tunai dengan penandatanganan sebagai perantara lease back', 0, 'J',  true);
            $this->pdf->Ln();

            $this->pdf->SetXY(10, 217);
            $this->pdf->MultiCell(190, 6.7, 'Demikian surat pernyataan ini saya buat untuk dipergunakan dengan semestinya.', 0, 'L',  true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 224);
            $this->pdf->MultiCell(190, 6.7, 'Saya menyatakan bahwa keterangan-keterangan  dalam Surat Pernyataan ini adalah benar dan saya buat dengan sejujurnya, apabila dikemudian hari ternyata keterangan-keterangan di atas tidak sebenarnya saya sanggup mempertanggungjawabkannya dihadapan hukum.', 0, 'J',  true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 241);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()) . ',', 0, 'L',  true);
            $this->pdf->SetXY(10, 246);
            $this->pdf->MultiCell(55, 5, 'Pemberi pernyataan,,', 0, 'L',  true);
            $this->pdf->SetXY(10, 270);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);

            //SURAT PERNYATAAN 2
            $this->pdf->AddPage('P', 'A4');
            $this->header();

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'SURAT PERNYATAAN', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 6.7, 'Yang bertanda tangan dibawah ini', 0, '0', 'L', true);
            $this->pdf->Cell(4, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_pemilik), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Jabatan', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, "OWNER", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Dealer/Showroom', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, '', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, '', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->alamat_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, 'Sehubungan dengan kendaraan yang saya jual kepada :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->alamat, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, 'Sehubungan dengan data-data kendaraan sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Jenis', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, 'SEPEDA MOTOR', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->tahun_pembuatan . '   /' . $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Maka saya menyatakan', 0, '0', 'L', true);
            $this->pdf->Cell(4, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 171);
            $this->pdf->MultiCell(190, 6.7, 'Bahwa surat-surat kendaraan berupa BPKB, Faktur, Kwitansi Blanko, dll yang saya serahkan kepada ' . strtoupper($request->nama_leasing) . ' adalah ASLI dan Sah secara hukum serta tidak tersangkut perkara pidana atau perbuatan melawan hukum apapun.', 0, 'J',  true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 184);
            $this->pdf->MultiCell(190, 6.7, 'Bahwa surat-surat tersebut akan diteliti dan diperiksa keaslian dan keabsahannya oleh ' . strtoupper($request->nama_leasing) . ' kepada instansi yang berwenang terlebih dahulu sebelum ' . strtoupper($request->nama_leasing) . ' melakukan pembayaran kepada saya.', 0, 'J',  true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 198);
            $this->pdf->MultiCell(190, 6.7, 'Bahwa apabila ternyata hasil pemeriiksaan surat-surat tersebut di atas menunjukkan secara tegas atau ada indikasi surat-surat tersebut dan atau kendaraan tersebut tersangkut Tindak Pidana atau Perbuatan Melawan Hukum atau dalam keadaan diblokir, maka saya bersedia membatalkan transaksi tersebut dan tidak akan menuntut ' . strtoupper($request->nama_leasing) . ' baik Pidana atau Perdata.', 0, 'J',  true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 235);
            $this->pdf->MultiCell(190, 5, $setting->kota . ', ' . tanggal_hari(this_day()) . ' ,................................................', 0, 'L',  true);
            $this->pdf->SetXY(10, 240);
            $this->pdf->MultiCell(55, 5, 'Pemberi pernyataan,,', 0, 'L',  true);
            $this->pdf->SetXY(10, 270);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);

            //SURAT PERNYATAAN KEABSAHAN BPKB
            $this->pdf->AddPage('P', 'A4');

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'SURAT PERNYATAAN KEABSAHAN BPKB', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 6.7, 'Yang bertanda tangan dibawah ini', 0, '0', 'L', true);
            $this->pdf->Cell(4, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_pemilik), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Bertindak atas nama showroom', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->alamat_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, 'Menyatakan bahwa objek pendanaan sepeda motor ke ' . strtoupper($request->nama_leasing) . 'Tasikmalaya dengan data-data sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Jenis', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, 'SEPEDA MOTOR', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->tahun_pembuatan . '   /' . $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Faktur', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, 'Asli / Copy / Tidak Ada *', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Atas Nama BPKB terakhir', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, 'Ada / Tidak Ada *', 0, '0', 'L', true);
            $this->pdf->Cell(20, 6.7, '*) coret yang tidak perlu', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 130);
            $this->pdf->MultiCell(190, 6.7, "Memang benar berasal dari showroom Kami dan menjadi objek pendanaan sepeda motor di " . strtoupper($request->nama_leasing) . " dan terikat serta wajib mematuhi dan menjamin bahwa :\n a. Kendaraan pada waktu pertama kali diserahkan kepada debitur memiliki surat-surat yang sah serta     tidak dalam sengketa, dijaminkan, dijual datau dialihkan kepada pihak manapun. \n b. Showroom memiliki ijin-ijin yang disyaratkan untuk menjalankan usaha sebagaimana mestinya dan dengan ini berjanji untuk memperpanjang dan atau memperbaharui ijin-ijin tersebut bilamana telah habis masa berlakunya apabila hal tersebut disyaratkan oleh peraturan yang berlaku \n c. Tidak ada suatu perkara perdata, tata usaha negara, tuntutan pajak, perkara pidana atau sengketa yang sedanga berlangsung yang mengancam atau dapat menimbulkan akibat terhadap showroom atau harta kekayaan showroom sehingga mempengaruhi usaha showroom \n d. Telah menyerahkan dengan lengkap dan benar dokumen-dokumen pengenal, perijinan, dan atau anggaran dasar showroom berikut perubahan dan atau tambahan dan terhadap anggaran dasar tersebut, pada saat ini tidak atau belum diadakan perubahan atau tambahan lagi berupa apapun juga \n e. Dalam membuat dan melaksanakan perjanjian ini showroom tidak melanggar atau bertentangan dengan undang-undang, peraturan pemerintah, kebijakan pemerintah, petunjuk atau instruksi pemerintah, keputusan pengadilan yang berlaku maupun anggaran dasar showroom maupun akan mengakibatkan cidera janji terhadap suatu perjanjian telah dibuat oleh showroom. \n f. Showroom menjamin dan wajib mengganti kerugian kepada pihak debitur dan " . strtoupper($request->nama_leasing) . " serta membebas dari segala gugatan, tuntutan, kewajiban dan atau kerugian termasuk biaya dan pengeluaran sehubungan dengan pengurusan pada status hukum dari dokumen-dokumen dan atau hal lainnya, yang termasuk namun tidak terbatas hal-hal yang dinyatakan dan dijamin dalam suatu pernyataan ini. \n\nDemikian surat pernyataan ini saya buat dengan sebenarnya dan dalam keadaan sadar tanpa ada tekanan dari pihak manapun agar dapat dipergunakan sebagaimana mestinya", 0, 'J',  true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 400);
            $this->pdf->MultiCell(190, 5, '', 0, 'L',  true);
            $this->pdf->SetXY(10, 20);
            $this->pdf->MultiCell(190, 5, $setting->kota . ', ' . tanggal_hari(this_day()) . ' ,................................................', 0, 'L',  true);
            $this->pdf->SetXY(10, 25);
            $this->pdf->MultiCell(55, 5, 'Yang membuat,', 0, 'L',  true);
            $this->pdf->SetXY(10, 55);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik . "\nPemilik / PIC Showroom", 0, 'L',  true);
            $this->pdf->SetXY(140, 25);
            $this->pdf->MultiCell(55, 5, 'Mengetahui,', 0, 'L',  true);
            $this->pdf->SetXY(140, 55);
            $this->pdf->MultiCell(55, 5, $data->nama . "\nNasabah", 0, 'L',  true);

            //KWITANSI KOMISI LANGSUNG
            $this->pdf->AddPage('P', 'A4');
            $this->header();

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'KOMISI LANGSUNG', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 7, 'Sudah Terima Dari', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($request->nama_leasing), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Uang sejumlah', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, rupiah($data->komisi), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, '', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, '', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, terbilang($data->komisi) . " Rupiah", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Untuk Pembayaran', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, 'Komisi langsung atas pembelian 1 (unit) Sepeda Motor dengan data-data sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->tahun_pembuatan, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(10, 130);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()), 0, 'L',  true);
            $this->pdf->SetXY(10, 160);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);
            $this->pdf->Ln();
            // Simpan file PDF ke server
            $this->pdf->Output('Cetak Tagihan ' . $data->nama . '.pdf', 'I');
            exit;
            //SIZE LEGAL --------------------------------------------------------------------------------------------------------------------------------------------------------
        } else if ($request->size == "Legal") {
            $this->pdf->AddPage('P', 'Legal');
            $this->header();
            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, "SURAT JALAN\n", '0', 1, 'C');
            $this->pdf->SetFont('Arial', 'U', '9');
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(10, 45);
            $this->pdf->MultiCell(196, 5, 'NO: ' . $data->nota, 0, 'C',  true);

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            $this->pdf->Cell(44, 7, 'Yang bertanda tangan dibawah ini', 0, '0', 'L', true);
            $this->pdf->Cell(4, 7, ':', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($setting->nama_pemilik), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($setting->alamat_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(100, 7, 'Dengan ini menyerahkan 1(satu) unit sepeda motor:', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->tahun_pembuatan, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Nama Nasabah', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, $data->alamat, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Hp', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, $data->no_telepon, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(145, 140);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()), 0, 'L',  true);
            $this->pdf->SetXY(9, 145);
            $this->pdf->MultiCell(55, 5, 'Yang menerima', 0, 'L',  true);
            $this->pdf->SetXY(145, 145);
            $this->pdf->MultiCell(55, 5, 'Yang menyerahkan', 0, 'L',  true);
            $this->pdf->SetXY(9, 175);
            $this->pdf->MultiCell(55, 5, '(..............................................)', 0, 'L',  true);
            $this->pdf->SetXY(145, 175);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);
            $this->pdf->Ln();

            //KWITANSI PELUNASAN
            // $this->pdf->AddPage('P', 'Legal');
            // $this->header();

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'KWITANSI PELUNASAN', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 7, 'Sudah Terima Dari', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($request->nama_leasing) . "   QQ " . strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Untuk Pembayaran', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, 'Pelunasan 1 (unit) Sepeda Motor dengan data-data Sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->tahun_pembuatan, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Pelunasan', 0, '0', 'L', true);
            $this->pdf->Cell(38, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, rupiah($data->pencairan) . " (" . terbilang($data->pencairan) . " Rupiah)", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(145, 290);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()), 0, 'L',  true);
            $this->pdf->SetXY(145, 320);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);
            $this->pdf->Ln();


            //KWITANSI UANG MUKA
            $this->pdf->AddPage('P', 'Legal');
            $this->header();

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'KWITANSI UANG MUKA', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 7, 'Sudah Terima Dari', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Untuk Pembayaran', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, 'Down Payment 1 (unit) Sepeda Motor dengan data-data Sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->tahun_pembuatan, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Uang Muka', 0, '0', 'L', true);
            $this->pdf->Cell(38, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, rupiah($data->dp_po) . " (" . terbilang($data->dp_po) . " Rupiah)", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(145, 137);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()), 0, 'L',  true);
            $this->pdf->SetXY(145, 167);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);
            $this->pdf->Ln();

            //KWITANSI KOMISI LANGSUNG
            // $this->pdf->AddPage('P', 'Legal');
            // $this->header();

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'KOMISI LANGSUNG', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 7, 'Sudah Terima Dari', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($request->nama_leasing), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Uang sejumlah', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, rupiah($data->komisi), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, '', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, '', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, terbilang($data->komisi) . " Rupiah", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Untuk Pembayaran', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, 'Komisi langsung atas pembelian 1 (unit) Sepeda Motor dengan data-data sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, 'No Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(45, 7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->tahun_pembuatan, 0, '0', 'L', true);
            $this->pdf->Cell(44, 7, $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(10, 270);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()), 0, 'L',  true);
            $this->pdf->SetXY(10, 300);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);
            $this->pdf->Ln();

            //TANPA JUDUL 1
            $this->pdf->AddPage('P', 'Legal');
            $this->header();

            $this->pdf->Ln();
            $this->pdf->Ln();

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 7, 'Nama Nasabah', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Jenis Kendaraan', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, "SEPEDA MOTOR", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->tahun_pembuatan . '   /' . $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 7, 'No Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Asli", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Duplikat", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'Faktur', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'Kwitansi Blangko BBN atas nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'FC KTP atas nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'FC STNK dan Nota Pajak', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'Nomor Polisi Sesuai STNK & BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(80, 7, 'Noka dan Nosin Sesuai STNK & BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(25, 7, "Ada", 0, '0', 'L', true);
            $this->pdf->Cell(15, 7, "Tidak ada", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->SetFillColor(255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetXY(9, 220);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()) . ',', 0, 'L',  true);
            $this->pdf->SetXY(9, 225);
            $this->pdf->MultiCell(55, 5, 'Yang menyatakan,', 0, 'L',  true);
            $this->pdf->SetXY(9, 259);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);

            //KOTAK CEKLIS
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0, 0, 0);
            $this->pdf->SetDrawColor(0, 0, 0);
            //BPKB
            $this->pdf->SetXY(85, 115);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 115);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            //Faktur
            $this->pdf->SetXY(85, 122);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 122);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //Kwitansi Blangko BBN atas nama BPKB
            $this->pdf->SetXY(85, 129);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 129);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //FC KTP atas nama BPKB
            $this->pdf->SetXY(85, 136);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 136);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //FC STNK dan Nota Pajak
            $this->pdf->SetXY(85, 143);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 143);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //Nomor Polisi Sesuai STNK & BPKB
            $this->pdf->SetXY(85, 150);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 150);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //Noka dan Nosin Sesuai STNK & BPKB
            $this->pdf->SetXY(85, 157);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->SetXY(110, 157);
            $this->pdf->MultiCell(4, 4, '', 1, 'L',  true);
            $this->pdf->Ln();
            //Pernyataan
            $this->pdf->SetXY(9, 181);
            $this->pdf->MultiCell(190, 7, 'Apabila dikemudian hari diketahui bahwa surat-surat kendaraan tersebut di atas PALSU dan atau SEDANG DALAM PEMBLOKIRAN, maka dengan ini kami (dealer / sub dealer / showroom / perorangan) menyatakan "akan membeli kembali atau melunasi kendaraan tersebut di atas kepada ' . strtoupper($request->nama_leasing) . ' sesuai dengan perhitungan pelunasan dari ' . strtoupper($request->nama_leasing) . ' selambat-lambatnya 1 (satu) minggu sejak adanya pemberitahuan".', 0, 'J',  true);
            $this->pdf->Ln();

            //SURAT PERNYATAAN
            $this->pdf->AddPage('P', 'Legal');
            $this->header();

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'SURAT PERNYATAAN', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 6.7, 'Yang bertanda tangan dibawah ini', 0, '0', 'L', true);
            $this->pdf->Cell(4, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_pemilik), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Jabatan', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, "OWNER", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Dealer/Showroom', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, '', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, '', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->alamat_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, 'Menyatakan bahwa BPKB dengan data sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Jenis', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, 'SEPEDA MOTOR', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->tahun_pembuatan . '   /' . $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, 'Dengan ini menyatakan bahwa :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, '1. Telah menjual kendaraan tersebut kepada :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->alamat, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, '2. bahwa kendaraan tersebut diatas benar-benar milik penandatangan sendiri berdasarkan jual beli yang sah dari pemilik semula, yaitu :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->alamat_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, '3. Bahwa kendaraan tersebut di atas BUKAN TITIPAN PIHAK LAIN.', 0, '0', 'L', true);

            $this->pdf->SetXY(10, 197);
            $this->pdf->MultiCell(190, 6.7, '4. Bahwa penjulan kendaraan tersebut adalah penjualan langsung kepada pembeli tersebut di atas dengan jasa ' . strtoupper($request->nama_leasing) . ' sebagai kreditor dan BUKAN TRANSAKSI LEASE BACK atau menjaminkan kendaraan untuk mendapatkan uang tunai dengan penandatanganan sebagai atau menjaminkan kendaraan untuk mendapatkan uang tunai dengan penandatanganan sebagai perantara lease back', 0, 'J',  true);
            $this->pdf->Ln();

            $this->pdf->SetXY(10, 217);
            $this->pdf->MultiCell(190, 6.7, 'Demikian surat pernyataan ini saya buat untuk dipergunakan dengan semestinya.', 0, 'L',  true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 224);
            $this->pdf->MultiCell(190, 6.7, 'Saya menyatakan bahwa keterangan-keterangan  dalam Surat Pernyataan ini adalah benar dan saya buat dengan sejujurnya, apabila dikemudian hari ternyata keterangan-keterangan di atas tidak sebenarnya saya sanggup mempertanggungjawabkannya dihadapan hukum.', 0, 'J',  true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 241);
            $this->pdf->MultiCell(55, 5, $setting->kota . ', ' . tanggal_hari(this_day()) . ',', 0, 'L',  true);
            $this->pdf->SetXY(10, 246);
            $this->pdf->MultiCell(55, 5, 'Pemberi pernyataan,,', 0, 'L',  true);
            $this->pdf->SetXY(10, 270);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);

            //SURAT PERNYATAAN 2
            $this->pdf->AddPage('P', 'Legal');
            $this->header();

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'SURAT PERNYATAAN', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 6.7, 'Yang bertanda tangan dibawah ini', 0, '0', 'L', true);
            $this->pdf->Cell(4, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_pemilik), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Jabatan', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, "OWNER", 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Dealer/Showroom', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, '', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, '', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->alamat_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, 'Sehubungan dengan kendaraan yang saya jual kepada :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->alamat_bpkb, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, 'Sehubungan dengan data-data kendaraan sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Jenis', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, 'SEPEDA MOTOR', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->tahun_pembuatan . '   /' . $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Maka saya menyatakan', 0, '0', 'L', true);
            $this->pdf->Cell(4, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 171);
            $this->pdf->MultiCell(190, 6.7, 'Bahwa surat-surat kendaraan berupa BPKB, Faktur, Kwitansi Blanko, dll yang saya serahkan kepada ' . strtoupper($request->nama_leasing) . ' adalah ASLI dan Sah secara hukum serta tidak tersangkut perkara pidana atau perbuatan melawan hukum apapun.', 0, 'J',  true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 184);
            $this->pdf->MultiCell(190, 6.7, 'Bahwa surat-surat tersebut akan diteliti dan diperiksa keaslian dan keabsahannya oleh ' . strtoupper($request->nama_leasing) . ' kepada instansi yang berwenang terlebih dahulu sebelum ' . strtoupper($request->nama_leasing) . ' melakukan pembayaran kepada saya.', 0, 'J',  true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 198);
            $this->pdf->MultiCell(190, 6.7, 'Bahwa apabila ternyata hasil pemeriiksaan surat-surat tersebut di atas menunjukkan secara tegas atau ada indikasi surat-surat tersebut dan atau kendaraan tersebut tersangkut Tindak Pidana atau Perbuatan Melawan Hukum atau dalam keadaan diblokir, maka saya bersedia membatalkan transaksi tersebut dan tidak akan menuntut ' . strtoupper($request->nama_leasing) . ' baik Pidana atau Perdata.', 0, 'J',  true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 235);
            $this->pdf->MultiCell(190, 5, $setting->kota . ', ' . tanggal_hari(this_day()), 0, 'L',  true);
            $this->pdf->SetXY(10, 240);
            $this->pdf->MultiCell(55, 5, 'Pemberi pernyataan,,', 0, 'L',  true);
            $this->pdf->SetXY(10, 270);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik, 0, 'L',  true);

            //SURAT PERNYATAAN KEABSAHAN BPKB
            $this->pdf->AddPage('P', 'Legal');

            $this->pdf->SetFont('Arial', 'U', '16');
            $this->pdf->Cell(0, 16, 'SURAT PERNYATAAN KEABSAHAN BPKB', '0', 1, 'C');

            $this->pdf->SetFont('Arial', '', '8');
            $this->pdf->SetFillColor(255, 255, 255);
            $this->pdf->SetTextColor(0);
            // $this->pdf->SetDrawColor(255, 255, 255);
            $this->pdf->Cell(44, 6.7, 'Yang bertanda tangan dibawah ini', 0, '0', 'L', true);
            $this->pdf->Cell(4, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nama', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_pemilik), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Bertindak atas nama showroom', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->nama_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Alamat', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($setting->alamat_toko), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(100, 6.7, 'Menyatakan bahwa objek pendanaan sepeda motor ke ' . strtoupper($request->nama_leasing) . 'Tasikmalaya dengan data-data sebagai berikut :', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Jenis', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, 'SEPEDA MOTOR', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No Polisi', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->no_polisi, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'No BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(54, 6.7, $data->bpkb, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Atas Nama BPKB', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, strtoupper($data->nama_bpkb), 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Merk/Type', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->merek . ' ' . $data->type, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Tahun/Warna', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, $data->tahun_pembuatan . '   /' . $data->warna, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Rangka', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_rangka, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Nomor Mesin', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, $data->no_mesin, 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Faktur', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(145, 6.7, 'Asli / Copy / Tidak Ada *', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->Cell(44, 6.7, 'Atas Nama BPKB terakhir', 0, '0', 'L', true);
            $this->pdf->Cell(2, 6.7, ':', 0, '0', 'L', true);
            $this->pdf->Cell(30, 6.7, 'Ada / Tidak Ada *', 0, '0', 'L', true);
            $this->pdf->Cell(20, 6.7, '*) coret yang tidak perlu', 0, '0', 'L', true);
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 130);
            $this->pdf->MultiCell(190, 6.7, "Memang benar berasal dari showroom Kami dan menjadi objek pendanaan sepeda motor di " . strtoupper($request->nama_leasing) . " dan terikat serta wajib mematuhi dan menjamin bahwa :\n a. Kendaraan pada waktu pertama kali diserahkan kepada debitur memiliki surat-surat yang sah serta     tidak dalam sengketa, dijaminkan, dijual datau dialihkan kepada pihak manapun. \n b. Showroom memiliki ijin-ijin yang disyaratkan untuk menjalankan usaha sebagaimana mestinya dan dengan ini berjanji untuk memperpanjang dan atau memperbaharui ijin-ijin tersebut bilamana telah habis masa berlakunya apabila hal tersebut disyaratkan oleh peraturan yang berlaku \n c. Tidak ada suatu perkara perdata, tata usaha negara, tuntutan pajak, perkara pidana atau sengketa yang sedanga berlangsung yang mengancam atau dapat menimbulkan akibat terhadap showroom atau harta kekayaan showroom sehingga mempengaruhi usaha showroom \n d. Telah menyerahkan dengan lengkap dan benar dokumen-dokumen pengenal, perijinan, dan atau anggaran dasar showroom berikut perubahan dan atau tambahan dan terhadap anggaran dasar tersebut, pada saat ini tidak atau belum diadakan perubahan atau tambahan lagi berupa apapun juga \n e. Dalam membuat dan melaksanakan perjanjian ini showroom tidak melanggar atau bertentangan dengan undang-undang, peraturan pemerintah, kebijakan pemerintah, petunjuk atau instruksi pemerintah, keputusan pengadilan yang berlaku maupun anggaran dasar showroom maupun akan mengakibatkan cidera janji terhadap suatu perjanjian telah dibuat oleh showroom. \n f. Showroom menjamin dan wajib mengganti kerugian kepada pihak debitur dan " . strtoupper($request->nama_leasing) . " serta membebas dari segala gugatan, tuntutan, kewajiban dan atau kerugian termasuk biaya dan pengeluaran sehubungan dengan pengurusan pada status hukum dari dokumen-dokumen dan atau hal lainnya, yang termasuk namun tidak terbatas hal-hal yang dinyatakan dan dijamin dalam suatu pernyataan ini. \n\nDemikian surat pernyataan ini saya buat dengan sebenarnya dan dalam keadaan sadar tanpa ada tekanan dari pihak manapun agar dapat dipergunakan sebagaimana mestinya", 0, 'J',  true);
            $this->pdf->Ln();
            $this->pdf->Ln();
            $this->pdf->SetXY(10, 270);
            $this->pdf->MultiCell(190, 5, $setting->kota . ', ' . tanggal_hari(this_day()), 0, 'L',  true);
            $this->pdf->SetXY(10, 275);
            $this->pdf->MultiCell(55, 5, 'Yang membuat,', 0, 'L',  true);
            $this->pdf->SetXY(10, 305);
            $this->pdf->MultiCell(55, 5, $setting->nama_pemilik . "\nPemilik / PIC Showroom", 0, 'L',  true);
            $this->pdf->SetXY(140, 275);
            $this->pdf->MultiCell(55, 5, 'Mengetahui,', 0, 'L',  true);
            $this->pdf->SetXY(140, 305);
            $this->pdf->MultiCell(55, 5, $data->nama . "\nNasabah", 0, 'L',  true);

            // Simpan file PDF ke server
            $this->pdf->Output('Cetak Tagihan ' . $data->nama . '.pdf', 'I');
            exit;
        }
    }
}
